// ══════════════════════════════════════════════════════════════════════════
// BAL-1 (#471) — the balance sim, FULL run. This is the "one command":
//
//     npm run balance
//
// It plays N seeds per matchup with the scripted player bots
// (tests/unit/helpers/balance-sim.ts) and rewrites the harness-results block
// in docs/BALANCE.md — the report the ticket says is committed. Knobs:
//
//     BALANCE_SEEDS=1-30        the seed list (ranges and lists both parse)
//     BALANCE_MINUTES=25        the per-match window
//     BALANCE_REPORT=path.md    where the block lives (default docs/BALANCE.md)
//
// Heavy by design (≥30 seeds × 4 matchups = 120 whole matches): it is NOT in
// `npm test` (package.json excludes this file) and not in `test:slow` either
// — the smoke version below is. Targets and tolerances live in
// `TARGETS` / `*_TOLERANCE_*` in the helper so the smoke and the report can
// never disagree.
// ══════════════════════════════════════════════════════════════════════════
import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";

import {
  runBalanceMatch, summarize, summaryLine, arcTable, pct, BOTS, parseSeeds,
  WIN_RATE_TOLERANCE_PP, LENGTH_TOLERANCE_REL,
  MIN, type BalanceMatch, type BotKey, type MatchupSummary,
} from "./helpers/balance-sim";
import { RIVAL_SKILLS, ALL_SKILL_KEYS } from "../../src/iso/skill";
import {
  BASE_PRICE, BUILD_COSTS_MONEY, START_MONEY, VICTORY,
} from "../../src/iso/config";

const SEEDS = parseSeeds(process.env.BALANCE_SEEDS ?? "1-30");
const MINUTES = Number(process.env.BALANCE_MINUTES ?? 25);
const REPORT = path.resolve(
  process.env.BALANCE_REPORT ?? path.join(process.cwd(), "docs", "BALANCE.md"),
);
const BLOCK_BEGIN = "<!-- BALANCE-SIM:BEGIN — generated by `npm run balance`; do not edit by hand -->";
const BLOCK_END = "<!-- BALANCE-SIM:END -->";

/** The four matchups the ticket's targets name, plus one informational. */
const MATCHUPS: { bot: BotKey; difficulty: keyof typeof RIVAL_SKILLS }[] = [
  { bot: "steady", difficulty: "easy" },
  { bot: "steady", difficulty: "normal" },
  { bot: "steady", difficulty: "hard" },
  { bot: "novice", difficulty: "trainee" },
  { bot: "sharp", difficulty: "hard" },
];

/**
 * Tuning filter: `BALANCE_MATCHUPS=steady#easy` runs one matchup (and then
 * only that matchup may appear in the written block — set BALANCE_REPORT to
 * a scratch path when using it). Unset = the full matrix.
 */
const activeMatchups = ((): typeof MATCHUPS => {
  const raw = process.env.BALANCE_MATCHUPS;
  if (!raw) return MATCHUPS;
  const want = new Set(raw.split(",").map((s) => s.trim().toLowerCase()));
  return MATCHUPS.filter((m) => want.has(`${m.bot}#${m.difficulty}`));
})();

function knobTable(): string {
  const rows = ALL_SKILL_KEYS.map((k) => {
    const s = RIVAL_SKILLS[k];
    return `| ${s.label} | ${s.buildMs / 1000}s | ${s.idleMs / 1000}s | ${s.sessionMs / 1000}s | ${s.expandPerTurn} | ${s.paveTiles} | ${s.tuningSkill} | ${s.townReserve} | ${s.winTarget}★ |`;
  });
  return [
    "| Rival preset | build | idle | session | expand | pave | tune | townRsv | line |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    `★ line (\`VICTORY.loop.target\`): **${VICTORY.loop.target}★** · START_MONEY: **$${START_MONEY}**`,
    "",
    "| Good | BASE_PRICE | | Build | $ | | Bot | build | idle | session | tune | pave | townRsv | sell |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...Object.entries(BASE_PRICE).map(([c, p], i) => {
      const builds = Object.entries(BUILD_COSTS_MONEY);
      const b = builds[i] ?? ["", ""];
      const botKeys = Object.keys(BOTS) as BotKey[];
      const bk = botKeys[i];
      const bot = bk ? BOTS[bk] : null;
      return `| ${c} | $${p} | | ${b[0]} | $${b[1]} | | ${bot ? bot.key : ""} | ${bot ? bot.buildMs / 1000 + "s" : ""} | ${bot ? bot.idleMs / 1000 + "s" : ""} | ${bot ? bot.sessionMs / 1000 + "s" : ""} | ${bot ? bot.tuningSkill : ""} | ${bot ? bot.paveTiles : ""} | ${bot ? bot.townReserve : ""} | ${bot ? bot.sell : ""} |`;
    }),
  ].join("\n");
}

function verdict(s: MatchupSummary): string {
  const t = s.target;
  const parts: string[] = [];
  if (t.rivalWinRate !== null) {
    const ok = Math.abs(s.rivalWinRate - t.rivalWinRate) * 100 <= WIN_RATE_TOLERANCE_PP;
    parts.push(`${ok ? "✅" : "❌"} rival win rate ${pct(s.rivalWinRate)} vs target ${pct(t.rivalWinRate)} ±${WIN_RATE_TOLERANCE_PP}pp`);
  }
  if (t.meanMinutes !== null) {
    const lo = t.meanMinutes[0] * (1 - LENGTH_TOLERANCE_REL);
    const hi = t.meanMinutes[1] * (1 + LENGTH_TOLERANCE_REL);
    const ok = s.meanMinutes >= lo && s.meanMinutes <= hi;
    parts.push(`${ok ? "✅" : "❌"} mean length ${s.meanMinutes.toFixed(1)}m vs target ${t.meanMinutes[0]}–${t.meanMinutes[1]}m ±${(LENGTH_TOLERANCE_REL * 100).toFixed(0)}%`);
  }
  return parts.join(" · ");
}

function seedTable(ms: BalanceMatch[]): string {
  return [
    "| seed | winner | minutes | you ★ (dep/rte/city) | rival ★ (dep/rte/city) | you $ | rival $ | stalls (you/rival) |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...ms.map((m) => {
      const youStar = m.trace.length ? m.trace[m.trace.length - 1].youStar : 0;
      const aiStar = m.trace.length ? m.trace[m.trace.length - 1].aiStar : 0;
      const fmt = (s: BalanceMatch["you"]) => `${s.stars.types}/${s.stars.routes}/${s.stars.city}`;
      return `| ${m.seed} | ${m.winner ?? "—"} | ${MIN(m.endMs)} | ${youStar} (${fmt(m.you)}) | ${aiStar} (${fmt(m.ai)}) `
        + `| $${Math.round(m.you.money)} | $${Math.round(m.ai.money)} | ${m.you.turns.broke}/${m.ai.turns.broke} |`;
    }),
  ].join("\n");
}

function reportMarkdown(summaries: MatchupSummary[]): string {
  const lines: string[] = [];
  lines.push(`**Harness run** — ${new Date().toISOString().slice(0, 10)} · ${SEEDS.length} seeds (${SEEDS[0]}…${SEEDS[SEEDS.length - 1]}) · ${MINUTES} min window · targets within ±${WIN_RATE_TOLERANCE_PP}pp (win rates) / ±${(LENGTH_TOLERANCE_REL * 100).toFixed(0)}% (length).`);
  lines.push("");
  lines.push(knobTable());
  lines.push("");
  lines.push("### Verdict");
  lines.push("");
  for (const s of summaries) {
    lines.push(`- ${summaryLine(s)}`);
    lines.push(`  - ${verdict(s)}`);
  }
  lines.push("");
  for (const s of summaries) {
    lines.push(`### ${s.bot} vs ${s.difficulty} (n=${s.matches.length})`);
    lines.push("");
    lines.push(summaryLine(s));
    lines.push("");
    lines.push(arcTable(s, [0, 5, 10, 15, 20, 25]));
    lines.push("");
    lines.push(seedTable(s.matches));
    lines.push("");
  }
  return lines.join("\n");
}

/** Rewrite the generated block inside the report file. */
function writeReport(markdown: string): void {
  let doc = "";
  try {
    doc = fs.readFileSync(REPORT, "utf8");
  } catch {
    doc = `${BLOCK_BEGIN}\n${BLOCK_END}\n`;
  }
  const begin = doc.indexOf(BLOCK_BEGIN);
  const end = doc.indexOf(BLOCK_END);
  const next = begin >= 0 && end > begin
    ? doc.slice(0, begin) + `${BLOCK_BEGIN}\n${markdown}\n` + doc.slice(end)
    : `${doc.trim()}\n\n${BLOCK_BEGIN}\n${markdown}\n${BLOCK_END}\n`;
  fs.mkdirSync(path.dirname(REPORT), { recursive: true });
  fs.writeFileSync(REPORT, next);
}

describe("BAL-1 (#471) the balance sim — full run", () => {
  it(`plays ${SEEDS.length} seeds × ${activeMatchups.length} matchups and writes the report`, () => {
    const summaries = activeMatchups.map(({ bot, difficulty }) => {
      const matches = SEEDS.map((seed) => runBalanceMatch(seed, bot, difficulty, { minutes: MINUTES }));
      for (const m of matches) {
        console.log(`[balance] ${bot}#${difficulty} seed ${m.seed}: ${m.winner ?? "no decision"} at ${MIN(m.endMs)}`);
      }
      return summarize(bot, difficulty, matches);
    });
    for (const s of summaries) console.log(`[balance] ${summaryLine(s)} | ${verdict(s)}`);
    writeReport(reportMarkdown(summaries));
    console.log(`[balance] report written to ${REPORT}`);
    // The run itself must always succeed — the verdicts are the report's job.
    // What this asserts is the harness's own invariants: every match ran, and
    // a decided match has a winner inside the window with the loser scored.
    for (const s of summaries) {
      expect(s.matches.length).toBe(SEEDS.length);
      for (const m of s.matches) {
        if (m.winner) expect(m.endMs).toBeLessThanOrEqual(m.windowMs);
      }
    }
    expect(fs.existsSync(REPORT)).toBe(true);
  }, 10_800_000);
});
